version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: office_attendance_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: office_attendance
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
    container_name: office_attendance_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: office_attendance
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
